spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hope
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: false

jasypt:
  encryptor:
    password: password

jwt:
  secret: fortestfortestfortestfortestfortestfortestfortestfortestfortestfortestfortestfortestfortestfortestfortest
  expiration-period: 10000
