server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptEncryptor

spring:
  application:
    name: hope-gaarden
  profiles:
    active: local
    include: secret
  config:
    import: database.yml

application:
  security:
    jwt:
      secret-key: ENC(PdTZWTGeNGFBEwt24hCiiU/Ra5DKJ+Jt2eyTiAOyf2yzD8BhxV3e0n3Rm7dbh/yTYgAzW/DM5xpc5O8LfxOtPzfHEThMXppwrPijFvpOnes=)
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
