name: backend-test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # 실행 환경 (Git Runners 개인 서버)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # gradlew를 실행시키기 위해 권한 부여
      - name: Gradlew에게 실행권한 부여
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: |
          ./gradlew clean build --exclude-task test
