name: backend-test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # 실행 환경 (Git Runners 개인 서버)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # application.yml 파일 설정
      - name: resources 폴더 생성
        run: |
          mkdir -p ./application/src/main/resources

      - name: yml 파일 생성
        run: |
          echo "${{ secrets.APPLICATION_DEFAULT }}" > ./application/src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_LOCAL }}" > ./application/src/main/resources/application-local.yml
          echo "${{ secrets.APPLICATION_TEST }}" > ./application/src/main/resources/application-test.yml

      # gradlew를 실행시키기 위해 권한 부여
      - name: Gradlew에게 실행권한 부여
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: |
          cd ./application
          ./gradlew clean build -x test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Gradle 테스트
        run: |
          ./gradlew test

      - name: yaml 파일 변경
        run: |
          echo "${{ secrets.APPLICATION_DEFAULT_DEV }}" > ./backend/src/main/resources/application.yml
